bigcorp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django_email_verification import urls as email_urls

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("shop/", include("shop.urls", namespace="shop")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("", views.index, name="index"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from shop.views import category_list, products_detail_view

from .views import (
    cart_add,
    cart_view,
)

app_name = "cart"

urlpatterns = [
    path("", cart_view, name="cart-view"),
    path("add/", cart_add, name="add_to_cart"),
]

shop/urls.py
from django.urls import path

from .views import (ProductListView, category_list, products_detail_view,
                    search_products)

app_name = 'shop'

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path("search_products/", search_products, name="search-products"),
    path('search/<slug:slug>/', category_list, name='category-list'),
    path('<slug:slug>/', products_detail_view, name='product-detail'),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
import random
import string

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    """
    Model representing a category.

    Attributes:
        name (str): The name of the category.
        parent (Category): The parent category.
        slug (str): The URL slug of the category.
        created_at (datetime): The date and time of creation.

    """
    name = models.CharField("Категория", max_length=250, db_index=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children', blank=True, null=True
                               )
    slug = models.SlugField('URL', max_length=250,
                            unique=True, null=False, editable=True)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)

    class Meta:
        unique_together = (['slug', 'parent'])
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        """
        Returns a string representation of the object.
        """
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return ' > '.join(full_path[::-1])
    
    @staticmethod
    def _rand_slug():
        """
        Generates a random slug consisting of lowercase letters and digits.

        Example:
            >>> rand_slug()
            'abc123'
        """
        return ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(3))

    def save(self, *args, **kwargs):
        """
        Save the current instance to the database.
        """

        if not self.slug:
            self.slug = slugify(self._rand_slug() + '-pickBetter' + self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("shop:category-list", args=[str(self.slug)])


class Product(models.Model):
    """
    A model representing a product.

    """
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='products')
    title = models.CharField("Название", max_length=250)
    brand = models.CharField("Бренд", max_length=250)
    description = models.TextField("Описание", blank=True)
    slug = models.SlugField('URL', max_length=250)
    price = models.DecimalField(
        "Цена", max_digits=7, decimal_places=2, default=99.99)
    image = models.ImageField(
        "Изображение", upload_to='images/products/%Y/%m/%d', default='products/products/default.jpg')
    available = models.BooleanField("Наличие", default=True)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField('Дата изменения', auto_now=True)
    discount = models.IntegerField(
        default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("shop:product-detail", args=[str(self.slug)])

    def get_discounted_price(self):
        """
        Calculates the discounted price based on the product's price and discount.
        
        Returns:
            decimal.Decimal: The discounted price.
        """
        discounted_price = self.price - (self.price * self.discount / 100)
        return round(discounted_price, 2)

    @property
    def full_image_url(self):
        """
        Returns:
            str: The full image URL.
        """
        return self.image.url if self.image else ''


class ProductManager(models.Manager):
    def get_queryset(self):
        """
        Returns a queryset of products that are available.

        Returns:
            QuerySet: A queryset of products that are available.
        """
        return super(ProductManager, self).get_queryset().filter(available=True)


class ProductProxy(Product):

    objects = ProductManager()

    class Meta:
        proxy = True

bigcorp/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'bigcorp/index.html')

cart/views.py
from urllib import response
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from stripe import Product

from cart.cart import Cart
from shop.models import ProductProxy


def cart_view(request):
    cart = Cart(request)
    return render(request, "cart/cart-view.html")


def cart_add(request): 
    cart = Cart(request)

    if request.POST.get("action") == "post":
        product_id = int(request.POST.get("product_id"))
        product_qty = int(request.POST.get("product_qty"))

        product = get_object_or_404(ProductProxy, id=product_id)

        cart.add(product= product, quantity = product_qty)

        cart_qty = cart.__len__()

        response = JsonResponse({"qty": cart_qty, 'product': product.title})

        return response

def cart_delete(request): ...


def cart_update(request): ...

shop/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView

from .models import Category, ProductProxy


# def products_view(request):
#     products = ProductProxy.objects.all()
#     return render(request, 'shop/products.html', {'products': products})
class ProductListView(ListView):
    model = ProductProxy
    context_object_name = "products"
    paginate_by = 15

    def get_template_names(self):
        if self.request.htmx:
            return "shop/components/product_list.html"
        return "shop/products.html"


def products_detail_view(request, slug):
    product = get_object_or_404(
        ProductProxy.objects.select_related('category'), slug=slug)

    if request.method == 'POST':
        if request.user.is_authenticated:
            if product.reviews.filter(created_by=request.user).exists():
                messages.error(
                    request, 'You have already made a review for this product.')
            else:
                rating = request.POST.get('rating', 3)
                content = request.POST.get('content', '')
                if content:
                    product.reviews.create(
                        rating=rating, content=content, created_by=request.user, product=product)
                    return redirect(request.path)
        else:
            messages.error(
                request, 'You need to be logged in to make a review.')

    context = {'product': product}
    return render(request, 'shop/product_detail.html', context)

def category_list(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = ProductProxy.objects.select_related('category').filter(category=category)
    context = {'category': category, 'products': products}
    return render(request, 'shop/category_list.html', context)

def search_products(request):
    query = request.GET.get('q')
    products = ProductProxy.objects.filter(title__icontains=query).distinct()
    context = {'products': products}
    if not query or not products:
        return redirect('shop:products')
    return render(request, 'shop/products.html', context)

bigcorp/templates/bigcorp/index.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Welcome to BigCorp</title>
    <link rel="stylesheet" href="{% static 'bigcorp/css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'fonts/montserrat:wght@300,400,500.css' %}"/>
  </head>

  <body style="font-family: 'Montserrat', sans-serif;">
    <div id="welcome" class="welcome" >Welcome to BigCorp</div>
    <a href="http://127.0.0.1:8000/shop/"><div id="box1" class="box box1">Shop</div></a>
    <div class="box box2">News</div>
    <div class="box box3">Etc</div>
  </body>

<script src="{% static 'bigcorp/js/box-change.js' %}"></script>

</html>

cart/templates/cart/cart-view.html
{% include "base.html" %} {% load static %} {% block content %}

<main class="pt-5">
  <div class="container">
    <h1 class="h5">Shopping cart</h1>

    <hr />

    <br />

    <div class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <img
          class="img-fluid mx-auto d-block"
          width="200px"
          alt="Responsive image"
          src="{{product.full_image_url}}"
        />
      </div>

      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a
          href="{{product.get_absolute_url}}"
          class="text-info text-decoration-none"
        >
          <h1 class="h5 pt-2">title</h1>
        </a>

        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Product</div>

              <div class="col-6 text-end">
 

                <span class="h6 fw-bold">$ 1.99</span>

              </div>
            </div>
          </div>

          <div class="col">
            <div class="row p-3">
              <div class="col-12">
                <label for="select">Qty</label>

                &nbsp;

                <select id="select">
                  <option selected></option>

                  <option value="">1</option>

                  <option value="">2</option>

                  <option value="">3</option>

                  <option value="">4</option>
                </select>

                <br />
                <br />

                <button
                  type="button"
                  data-index=""
                  class="btn btn-primary btn-sm update-button"
                >
                  Update
                </button>

                &nbsp;

                <button
                  type="button"
                  class="btn btn-danger btn-sm delete-button"
                  data-index=""
                >
                  Delete
                </button>

                
              </div> 
      
              
            </div>
            
          </div>
          
        </div>
        
      </div>
      
    </div>
 
    
    <div class="col-12 text-end">
      <div class="h6 fw-bold">
        Total: $
        <div id="total" class="d-inline-flex"> 
        </div>
      </div>
      <button
                  type="button"
                  class="btn btn-success btn-md text-bg-light mt-4"
            
                >
                <a class="nav-link text-decoration-none" href="">Checkout</a>
                </button>
    </div>
  </div>

  <br />
  <br />
</main>

<script>
</script>

{% endblock %}

shop/templates/base.html
{% load static %}

<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Head imports -->
    {% include 'shop/_partials/_head_imports.html' %}
    <!-- Title -->
    <title>{% block title %} Home {% endblock %}</title>
    <!--Custom CSS -->
    <link rel="stylesheet" href="{% static 'shop/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/montserrat:wght@300,400,500.css' %}"/>
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'shop/images/favicon.ico' %}" >
    {% block head %} {% endblock head %}
  </head>

  <body>
    <!-- Navbar -->
    {% include 'shop/_partials/_navbar.html' %}

    <!-- Messages -->
    {% include 'shop/_partials/_messages.html' %}
    <main>
      <!-- Content -->
      {% block content %} {% endblock %}
    </main>
    <!-- Footer -->
    {% include 'shop/_partials/_footer.html' %}
  </body>

  <!-- Script -->
  <script src="{% static 'shop/js/base.js' %}" ></script>
  <script src="https://unpkg.com/htmx.org@1.9.9" integrity="sha384-QFjmbokDn2DjBjq+fM+8LUIVrAgqcNW2s0PjAxHETgRn9l4fvX31ZxDxvwQnyMOX" crossorigin="anonymous"></script>
</html>

shop/templates/shop/_partials/_footer.html
 <!-- Footer -->
 <footer id="main-footer" class="py-4 --bs-light-bg-subtle text-dark text-center">
    Copyright &copy;
    <span class="year"></span> BigCorp Shop
  </footer>

shop/templates/shop/_partials/_head_imports.html
<!-- CSS -->

<link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

<!-- JavaScript -->

<script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

<!-- JavaScript Bundle with Popper -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

shop/templates/shop/_partials/_messages.html
{% if messages %}
{% for message in messages %}
<div id="message" class="container">
    <div class="alert {{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            ERROR: {{ message }}
            {% else %}
            {{ message.tags|title}}
            {% endif %}
        </strong>
        {{ message }}
    </div>
</div>
{% endfor %}
{% endif %}

shop/templates/shop/_partials/_navbar.html
<nav class="navbar navbar-expand-lg bg-white sticky-top navbar-light p-3 shadow-sm ">
    <div class="container">
        <a class="navbar-brand" href=""><i class="fa-solid fa-shop me-2"></i>
            <strong>BigCorp SHOP</strong></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <form action="" method="get">
            <div class="mx-auto my-3 d-lg-none d-sm-block d-xs-block">
            <div class="input-group">
                <span class="border-success input-group-text bg-success text-white"><i
                        class="fa-solid fa-magnifying-glass"></i></span>
                <input type="text" name="q" placeholder="ex. Samsung" class="form-control border-success" style="color: #7a7a7a" />
                <button class="btn btn-success text-dark search-button">Search</button>
            </div>
        </div>
    </form>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <form action="" method="get">
            <div class="ms-auto d-none d-lg-block">
                <div class="input-group">
                    <span class="border-success input-group-text text-white search-button"><i
                            class="fa-solid fa-magnifying-glass"></i></span>
                    <input type="text" name="q" placeholder="ex. Samsung" class="form-control border-success" style="color: #7a7a7a" />
                    <button class="btn btn-success text-dark search-button">Search</button>
                </div>
            </div>
        </form>
            <ul class="navbar-nav ms-auto">
                {% for i in categories %}

                {% if not i.children.all %}
                <li class="nav-item">
                    <a class="nav-link" href="{{i.get_absolute_url}}">{{i.name|upper }}</a>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{{i.get_absolute_url}}" id="navbarDropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{i.name|upper}}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% for obj in i.children.all %} {% if not obj.children.all %}
                        <li><a class="dropdown-item" href="{{obj.get_absolute_url}}">{{obj.name|upper}}</a></li>
                        {% else %}
                        <li class="dropdown-submenu">
                            <a class="dropdown-item dropdown-toggle"
                                href="{{obj.get_absolute_url}}">{{obj.name|upper}}</a>

                            <ul class="dropdown-menu">
                                {% for subobj in obj.children.all %} {% if not subobj.children.all %}
                                <li>
                                    <a class="dropdown-item"
                                        href="{{subobj.get_absolute_url}}">{{subobj.name|upper}}</a>
                                </li>
                                {% else %}
                                <li class="dropdown-submenu">
                                    <a class="dropdown-item dropdown-toggle"
                                        href="{{subobj.get_absolute_url}}">{{subobj.name|upper}}</a>

                                    <ul class="dropdown-menu">
                                        {% for lastobj in subobj.children.all %}
                                        <li>
                                            <a class="dropdown-item"
                                                href="{{lastobj.get_absolute_url}}">{{lastobj.name|upper}}</a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </li>
                                {% endif %} {% endfor %}
                            </ul>
                        </li>
                        {% endif %} {% endfor %}
                    </ul>
                </li>
                {% endif %} {% endfor %}
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link mx-2 text-uppercase" href="{% url "cart:cart-view" %}"> <i
                            class="fa fa-shopping-cart" aria-hidden="true"> </i> Cart
                        <span id="lblCartCount" class="badge badge-warning ">

                            {% with cart_qty=cart|length%}
                            {% if cart_qty > 0 %}
                            {{cart_qty}}
                            {% else %}
                            0
                            {% endif %}

                            {% endwith %}
                        </span>
                    </a>
                </li>
                {% if request.user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link mx-2 text-uppercase" href=" "><i
                            class="fa-solid fa-circle-user me-1"></i>@{{ user.username }} Account</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link mx-2 text-uppercase" href=" "><i
                            class="fa-solid fa-circle-user me-1"></i> Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link mx-2 text-uppercase" href=" "><i
                            class="fa-solid fa-circle-user me-1"></i> Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link mx-2 text-uppercase" href=" "><i
                            class="fa-solid fa-circle-user me-1"></i> Login</a>
                </li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>

shop/templates/shop/category_list.html
{% extends "base.html" %}

{% load static %}


{% block content %}


<main>
  
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5"> {{category.name|capfirst}} </div>


      <hr>

      <br>


      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

      {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-info text-decoration-none" href="{{product.get_absolute_url}}"> {{product.title|capfirst}} </a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <h5> $ {{product.price}} </h5>
              </div>
            </div>
          </div>
        </div>

       {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

shop/templates/shop/components/product_list.html
{% load thumbnail%}
{% for product in products %}

{% if forloop.last %}
<div class="col" >
    {% else %}
    <div class="col">
        {% endif %}
        <a class="text-black text-decoration-none fs-4" href="{{product.get_absolute_url}}">
            <div class="card shadow-sm h-100">
                {% comment %} {% thumbnail product.image "400x400" as im %} {% endcomment %}
                <img class="img-fluid h-100" alt="Responsive image" src="{{ product.image.url }}" />
                {% comment %} {% endthumbnail %} {% endcomment %}
                <div class="card-body">
                    <p class="card-text">
                        {{product.title|capfirst}}
                    </p>
                    <div class="d-flex justify-content-between align-items-center badge search-button text-wrap text-dark"
                        style="width: 6rem">
                        <h5>$ {{product.price}}</h5>
                    </div>
                </div>
            </div>
        </a>
    </div>
{% endfor %}

shop/templates/shop/product_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="container">

    <main class="pt-5">

        <div class="row g-3">

            <div class="col-md-5 col-lg-5 order-md-first bg-light">

                <img class="img-fluid mx-auto d-block" alt="Responsive image" src="{{product.full_image_url}}">
                <!-- Product image -->

            </div>

            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">

                <h1 class="mb-0 h4"> {{product.title}}</h1>

                <strong>{{product.brand}}</strong>


                <hr>

                <br>


                <p> {{product.description}} </p>

                <div class="border">

                    <div class="col border-bottom">

                        <div class="row p-3">
                            <div class="col-6"> Price </div>
                            {% if product.discount %}
                            <div class="col-6 text-end"><span class="text-decoration-line-through fw-bold text-danger">$ {{product.price}} <span class="badge rounded-pill bg-info">discount</span></span> <span class="h4 fw-bold">$ {{product.get_discounted_price}}</span></div>
                            {% else%}
                            <div class="col-6 text-end"><span class="h4 fw-bold">$ {{product.price}}</span></div>
                            {% endif %}

                        </div>

                    </div>

                    <div class="col">

                        <div class="row p-3">

                            <div class="col-6">


                                <label for="select">Qty</label>

                                &nbsp;

                                <select id="select">

                                    <option value="1">1</option>

                                    <option value="2">2</option>

                                    <option value="3">3</option>

                                    <option value="4">4</option>

                                </select>

                            </div>

                            <div class="col-6 text-end">

                                <button type="button" id="add-button" value="{{product.id}}"
                                    class="btn btn-secondary btn-sm">

                                    Add to cart

                                </button>


                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </main>

    <br>

    {% comment %} {% include 'recommend/recommendation.html' %} {% endcomment %}

</div>

<script>

$(document).on('click', '#add-button', function(e){
    e.preventDefault();

    $.ajax({
        type:'POST',
        url:'{% url "cart:add_to_cart" %}',
        data:{
            product_id: $(this).val(),
            product_qty: $('#select option:selected').text(),
            csrfmiddlewaretoken: '{{ csrf_token }}',
            action: 'post'
        },
        success: function(response){
            document.getElementById("lblCartCount").textContent = response.qty
        },
        error: function(error){
            console.log("error: ",error)
        }
    })
})

</script>

{% endblock %}

shop/templates/shop/products.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block content %}

<!-- Introduction section -->
{% if not request.user.is_authenticated %}
<section class="py-4 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h4>Choose and it is in your hands.</h4>

      <br />

      <p class="lead text-muted">Browse and make the best deal</p>

      <br />

      <a href="#" class="btn btn-success my-2"> Create an account </a>
    </div>
  </div>
</section>
{% endif %}

<!-- All products section -->

<section class="album py-5 bg-light">
  <div class="container">
    <div class="pb-3 h5">All products</div>

    <hr />

    <br />

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

      {% include 'shop/components/product_list.html' %}
    </div>
  </div>
</section>
{% endblock %}